### ISSUE TITLE
Deploy Maven build artifacts to GitHub Packages Repository

### ISSUE THREAD

**Issue by ChristopheClermont** [sentrysoftware/workflows#19]
# Maven Build

Add GitHub Packages deployment action using Maven Settings.

**Comment by bertysentry** [comment]
The original goal was to upload the artifacts "somewhere" so it's available in the PRs that run this action as a check, and a tester could download the artifact and test it.

Deploying the artifact in GitHub Packages with `mvn deploy` makes it more difficult to retrieve the artifacts if several PRs are running at the same time.
