### ISSUE TITLE
Upload artifacts built with the GitHub Action in maven-build.yml

### ISSUE THREAD

**Issue by bertysentry** [sentrysoftware/workflows#21]
During the execution of an action, a GitHub action has the possibility to "upload" artifacts, which are then available to download for anyone.

This would help testers access the artifacts that are built for a PR.

See https://github.com/actions/upload-artifact

**Comment by ChristopheClermont** [comment]
Here the goal to achieve is to get the packages available from the "Packages" view of the repository.

We can use the GitHub Upload action, but it requires to specify the path of every file we need to upload... which may vary a lot!

Instead, I proposed to use the Maven deployment mechanism which knows exactly was files to upload. Thus this solution is the recommended one in [GitHub Packages documentation](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry).

**Comment by ChristopheClermont** [comment]
Fixed with https://github.com/sentrysoftware/workflows/pull/27
